# -*- coding: utf-8 -*-
"""pandaserieslab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1owO0N-8-QR55qjmNrqS8c98zcNJG-p6U
"""

import pandas as pd

marks = [45, 67, 89, 34, 90, 55, 72]
subjects = ['Math', 'Physics', 'Chemistry', 'English', 'CS', 'Biology', 'History']

s = pd.Series(marks, index=subjects)

# Subjects with marks > 70
print(s[s > 70])

# Replace marks < 40 with "Fail"
s_replaced = s.copy()
s_replaced[s < 40] = "Fail"
print(s_replaced)

# Count subjects above average
avg = s.mean()
count = (s > avg).sum()
print(count)

salary = [25000, 32000, 28000, 40000, 50000]
emp = ['A', 'B', 'C', 'D', 'E']

s = pd.Series(salary, index=emp)

# Increase 10% where salary < 30000
s[s < 30000] *= 1.10

# Decrease 5% where salary > 45000
s[s > 45000] *= 0.95

# Total salary expense
print(s.sum())

data = [10, None, 30, None, 50, 60, None]
s = pd.Series(data)

# Count missing before
before = s.isna().sum()

# Fill with mean
s = s.fillna(s.mean())

# Count after
after = s.isna().sum()

# Drop remaining nulls
s = s.dropna()

print(before, after)

marks = [95, 82, 67, 58, 73, 49, 88]
students = ['S1','S2','S3','S4','S5','S6','S7']

s = pd.Series(marks, index=students)

def grade(x):
    if x >= 90:
        return 'A'
    elif x >= 75:
        return 'B'
    elif x >= 60:
        return 'C'
    else:
        return 'D'

grades = s.apply(grade)

# Count each grade
print(grades.value_counts())

s1 = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
s2 = pd.Series([5, 15, 25], index=['B', 'C', 'D'])

# Addition
result = s1 + s2
print(result)

# Replace NaN with 0 and recompute
result_fixed = s1.add(s2, fill_value=0)
print(result_fixed)

scores = [88, 92, 79, 93, 85]
players = ['P1','P2','P3','P4','P5']

s = pd.Series(scores, index=players)

# Rank
ranks = s.rank(ascending=False)

# Top 3 players
top3 = s.sort_values(ascending=False).head(3)

# Lowest score player
lowest = s.idxmin()

print(ranks)
print(top3)
print(lowest)

names = ['anuj', 'rahul', 'sneha', 'kiran', 'amit']
s = pd.Series(names)

# Uppercase
print(s.str.upper())

# Names containing 'a'
print(s[s.str.contains('a')])

# Replace name
s = s.replace('anuj', 'Anuj Kumar')
print(s)

data = [5, None, 15, 25, None, 35, 45]
s = pd.Series(data)

result = (
    s.fillna(s.median())
     .loc[lambda x: x > 20]
     .sort_values(ascending=False)
     .reset_index(drop=True)
)

print(result)

sales = [200, 450, 300, 150, 500, 700, 100]
days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']

s = pd.Series(sales, index=days)

# Best & worst day
best = s.idxmax()
worst = s.idxmin()

# Total & average
total = s.sum()
avg = s.mean()

# Apply 20% bonus where sales > 400
bonus = s.copy()
bonus[s > 400] *= 1.2

# Sort descending
sorted_sales = s.sort_values(ascending=False)

print(best, worst)
print(total, avg)
print(bonus)
print(sorted_sales)