# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PO8ThmTwmthMLrfRQucapKoxvN9L0US
"""

import pandas as pd
#creating a series with dictionary
product_info=pd.Series({'Keyboard': 560,'Mouse':700,'Monitor':500,'Tablet':800,'Printer':500})
#to display series
print("Product with available quantity:")
print(product_info)
#display the products having quantity greater than 800
print("Products with quantity>800")
print(product_info>800)

# creating a series
marks=pd.Series([70,80,88,98,90,76,67,65,56,45,45,43,54,45,None,67,78,None,90,98,78])
print("Series is:")
print(marks)
#to display first 5 values
print("First 5 values")
print(marks.head(5))
print("------------------------------")
#to display last 7 values
print("last 7 values:")
print(marks.tail(7))
#to count the frequency of each value
print("Frequency of each value:")
print(marks.value_counts())

#to display unique values
print("Unique values")
print(marks.unique())

#to display count of unique values
print("Total unique values",marks.nunique())

#------------------------------
#creating a series
data = pd.Series([78,90,45,90,79],index=['Hindi','Science','English','Maths','Computer'])
#to sort the data as per values
print(data.sort_values())
#to sort data as per index
print("--------------------")
print("Sorted data as per index:")
print(data.sort_index())

#
data=pd.Series([50,60,80,None,90,50,None])
print(data.isnull())

data=pd.Series([50,60,None,90,50,None])
print(data.isnull())

import numpy as np
data1=pd.Series([50,60,None,90,30,np.nan,90,60,None])
#to fill empty value with 0
print(data1.fillna(0))



data2=pd.Series([50,60,None,60,90,None,20,None])
#misisng value treatment by filling data as average value
print(data2.fillna(data2.mean()))

data3=pd.Series([60,90,None,50,34,None,None,78])
#dropping missing value
print(data3.dropna())